lua/ulx/modules/sh/cfc_cleanup.lua

change category name to cleanup add `ulx cleanup

Cleanup commands

---

lua/ulx/modules/sh/cfc_cleanup.lua

i keep accidentally forgetting this  argument

make argument optional cleanup model

---

lua/ulx/modules/sh/cfc_owoify.lua

Previously, cfc_owoify.lua was interfering with ulx gimp and ulx mute, it now behaves as a third state of gimp.

Fix cfc_owoify to comply with mute/gimp

---

lua/ulx/modules/sh/timed_gag.lua

Kinda yucky imo, would love some suggestions on how to clean this up, if at all.

Adding a method to removing timed gags from a player

---

lua/ulx/modules/sh/cfc_setshadow.lua

setshadow should remove or add shadows to the selected players props

Add ulx setshadow

---

lua/ulx/modules/sh/cfc_clearpac.lua

Used for when a player is abusing pac so staff can clear their pac. This is written in the browser didn't test it yet

Add ulx clearpac command

---

lua/ulx/modules/sh/cfc_weprem.lua

Kanban card: https://kanban.cfcservers.org/b/zTdv2hrDmprDAKfxz/cfc-public/gRjyNtZpejyDHCzgj

Add weprem ulx command

---

lua/ulx/modules/sh/cfc_warn_after.lua

Add warnbanid, functions like warnban but instead uses banid

Add warnbanid

---

lua/ulx/modules/sh/cfc_propify.lua

Fixes a nil error and chat spam problem related to struggling/grabbing with propify.

Fix propify grab

---

lua/ulx/modules/sh/cfc_arrest.lua
lua/ulx/modules/sh/cfc_halt.lua

This pr adds a command that allows staff to freeze props, jails the targets and stops their sf / e2's

Add ulx arrest

---

lua/entities/train_fucked/cl_init.lua
lua/ulib/modules/cfc_timed_commands.lua
lua/ulx/modules/sh/cfc_checkfriends.lua

I noticed a couple of spacing issues while looking at the code which I couldn't ignore and fixed them too.

Fix checkfriend's silent message not showing the targeted player properly

---

lua/entities/train_fucked/init.lua
lua/entities/train_fucked/shared.lua

Fixes trainfuck being invisible / causing death errors.

Make trainfuck work on TTT

---

lua/ulx/modules/sh/cfc_propify.lua

Just forgot to include the return statement lmao

Ensure gravgun pickup is blocked when needed

---

lua/ulx/modules/sh/timed_pvp_ban.lua

Supports: https://github.com/CFC-Servers/cfc_pvp/pull/183

Update pvp method casing

---

lua/ulx/modules/sh/cfc_physgunallow.lua

Running this command on a player will allow them to be picked up by everyone

Add ulx physgunallow

---

lua/ulx/modules/sh/cfc_silent_ragdoll.lua

Add sragdoll and unsragdoll

---

lua/ulx/modules/sh/cfc_silent_ragdoll.lua

Make sragdoll unable to be used in pvp

---

lua/ulx/modules/sh/cfc_propify.lua

fixes error caused by trying to propify a player with the model being an effect

Fix null physics object error

---

lua/cfc_ulx_commands/curse/effects/drunk.lua

https://www.youtube.com/watch?v=CjCHZWbET_Y

Create drunk curse effect

---

README.md
lua/autorun/server/cfc_auto_warn_on_commands.lua
lua/ulx/modules/sh/timed_build_ban.lua

Ban build abusing players from buildmode

Add buildban

---

lua/cfc_ulx_commands/curse/effects/texture_shuffle.lua

Fixes a crash with `mat:SetTexutre( "$basetexture", nil )` caused by some materials not using a basetexture at all.
To do this, the cache check uses `~= nil` instead of truthy, stores nil textures as `false`, and then correctly uses `:SetUndefined()` to remove the basetexture instead of trying to apply a nil one.

Set undefined instead of nil

---

lua/cfc_ulx_commands/curse/effects/schizophrenia.lua

More stuff to really put people on edge and make them question what is and isn't real.

Improve Schizophrenia

---

lua/cfc_ulx_commands/curse/effects/do_no_harm.lua
lua/cfc_ulx_commands/curse/effects/do_some_harm.lua
lua/cfc_ulx_commands/curse/effects/ice_skates.lua

**DoNoHarm**: Prevents someone from damaging other players
**DoSomeHarm**: Prevents someone from damaging other players 75% of the time
**IceSkates**: Glorified zero-friction

Add DoNoHarm, DoSomeHarm, and IceSkates curse effects

---

lua/cfc_ulx_commands/curse/cl_utils.lua
lua/cfc_ulx_commands/curse/sv_utils.lua

In case any other addons want to listen for players having curses, to make them extra spicy

Add start/end curse hooks
